apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hospital-api-monitor
  namespace: monitoring   #  ADD THIS
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: hospital-api

  namespaceSelector:
    matchNames:
      - default   #  where your app is running

  endpoints:
    - port: http
      path: /metrics
      interval: 10s