apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
data:
  DB_HOST: hospital-postgres-db.cmb6ge6gu5ut.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: hospitalData
  DB_USER: postgres