pipeline {
    agent any

    stages {

        stage("Pull code from github") {
            steps {
                git branch: "main",
                url: "https://github.com/ashrafmusalman/doctor-api.git"
                echo "CODE PULLED SUCCESSFULL"
            }
        }

        stage("Build Docker Image") {
            steps {
                sh "docker build -t ashrafkhan0277/hospital-api:${BUILD_NUMBER} ."
            }
        }


// here we have been injecting 
        stage("Docker Hub Login") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "Jenkin-PAT",
                    usernameVariable: "DOCKER_HUB_USER",
                    passwordVariable: "DOCKER_HUB_PASS"
                )]) {
                    sh "echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin"
                }
            }
        }

        stage("Push Image") {
            steps { 
                sh "docker push ashrafkhan0277/hospital-api:${BUILD_NUMBER}"
            }
        }

       stage("Deploy to Kubernetes") {
    steps {
        sh """
        # Apply app resources
        kubectl apply -f k8s/

        # Apply monitoring resources separately
        kubectl apply -f k8s/monitoring/

        # Update image
        kubectl set image deployment/hospital-api \
        hospital-api=ashrafkhan0277/hospital-api:${BUILD_NUMBER}
        """
    }
}


    }
}
