pipeline {
    agent any

    stages {

        stage("Pull source codeee") {
            steps {
                git branch: "main",
                    url: "https://github.com/ashrafmusalman/doctor-api.git"
            }
        }

        stage("Building the containers") {
            steps {
                sh "docker compose build"
            }
        }

        stage("Docker Hub Login") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "jenkin-PAT",
                    usernameVariable: "DOCKER_HUB_USER",
                    passwordVariable: "DOCKER_HUB_PASS"
                )]) {
                    sh "echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin"
                }
            }
        }

        stage("Push to docker hub") {
            steps {
                sh "docker push ashrafkhan0277/hospital-api:1.0"
            }
        }

    }
}